server:
  port: 8087
eureka:
  instance:
    hostname: cloud.beetles.net
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://cloud.beetles.cn:8088/eureka/,http://cloud.beetles.com:8089/eureka/
