server:
  port: 7788
spring:
  application:
    name: springcloud-config-server
    #远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/cmaclcq/springcloudconfig.git
